/**
 * OpenParty API
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenPartyApi) {
      root.OpenPartyApi = {};
    }
    root.OpenPartyApi.Event = factory(root.OpenPartyApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Event model module.
   * @module model/Event
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Event</code>.
   * @alias module:model/Event
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Event} obj Optional instance to populate.
   * @return {module:model/Event} The populated <code>Event</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('event_id')) {
        obj['event_id'] = ApiClient.convertToType(data['event_id'], 'Number');
      }
      if (data.hasOwnProperty('event_title')) {
        obj['event_title'] = ApiClient.convertToType(data['event_title'], 'String');
      }
      if (data.hasOwnProperty('age_minimum')) {
        obj['age_minimum'] = ApiClient.convertToType(data['age_minimum'], 'String');
      }
      if (data.hasOwnProperty('event_description')) {
        obj['event_description'] = ApiClient.convertToType(data['event_description'], 'String');
      }
      if (data.hasOwnProperty('flyer_filename')) {
        obj['flyer_filename'] = ApiClient.convertToType(data['flyer_filename'], 'String');
      }
      if (data.hasOwnProperty('flyer_uri')) {
        obj['flyer_uri'] = ApiClient.convertToType(data['flyer_uri'], 'String');
      }
      if (data.hasOwnProperty('music_genres')) {
        obj['music_genres'] = ApiClient.convertToType(data['music_genres'], 'String');
      }
      if (data.hasOwnProperty('event_date')) {
        obj['event_date'] = ApiClient.convertToType(data['event_date'], 'String');
      }
      if (data.hasOwnProperty('start_time')) {
        obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
      }
      if (data.hasOwnProperty('event_subtitle')) {
        obj['event_subtitle'] = ApiClient.convertToType(data['event_subtitle'], 'String');
      }
      if (data.hasOwnProperty('venue')) {
        obj['venue'] = ApiClient.convertToType(data['venue'], 'String');
      }
      if (data.hasOwnProperty('featured')) {
        obj['featured'] = ApiClient.convertToType(data['featured'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Event Id.
   * @member {Number} event_id
   */
  exports.prototype['event_id'] = undefined;
  /**
   * Event Title.
   * @member {String} event_title
   */
  exports.prototype['event_title'] = undefined;
  /**
   * Age Minimum.
   * @member {String} age_minimum
   */
  exports.prototype['age_minimum'] = undefined;
  /**
   * Event Description.
   * @member {String} event_description
   */
  exports.prototype['event_description'] = undefined;
  /**
   * Flyer Filename.
   * @member {String} flyer_filename
   */
  exports.prototype['flyer_filename'] = undefined;
  /**
   * Flyer URI.
   * @member {String} flyer_uri
   */
  exports.prototype['flyer_uri'] = undefined;
  /**
   * Array of music genres.
   * @member {String} music_genres
   */
  exports.prototype['music_genres'] = undefined;
  /**
   * Event Date.
   * @member {String} event_date
   */
  exports.prototype['event_date'] = undefined;
  /**
   * Start time for the event.
   * @member {String} start_time
   */
  exports.prototype['start_time'] = undefined;
  /**
   * Event Subtitle.
   * @member {String} event_subtitle
   */
  exports.prototype['event_subtitle'] = undefined;
  /**
   * Venue Information with name, start time, default flyer, etc.
   * @member {String} venue
   */
  exports.prototype['venue'] = undefined;
  /**
   * If true, is ranked as one of most exciting event in Las Vegas.
   * @member {Boolean} featured
   */
  exports.prototype['featured'] = undefined;



  return exports;
}));


