/**
 * OpenParty API
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenPartyApi) {
      root.OpenPartyApi = {};
    }
    root.OpenPartyApi.Venue = factory(root.OpenPartyApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Venue model module.
   * @module model/Venue
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Venue</code>.
   * @alias module:model/Venue
   * @class
   */
  var exports = function() {
    var _this = this;































  };

  /**
   * Constructs a <code>Venue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Venue} obj Optional instance to populate.
   * @return {module:model/Venue} The populated <code>Venue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('venue_id')) {
        obj['venue_id'] = ApiClient.convertToType(data['venue_id'], 'Number');
      }
      if (data.hasOwnProperty('venue_type')) {
        obj['venue_type'] = ApiClient.convertToType(data['venue_type'], 'String');
      }
      if (data.hasOwnProperty('venue_title')) {
        obj['venue_title'] = ApiClient.convertToType(data['venue_title'], 'String');
      }
      if (data.hasOwnProperty('venue_display_title')) {
        obj['venue_display_title'] = ApiClient.convertToType(data['venue_display_title'], 'String');
      }
      if (data.hasOwnProperty('venue_description')) {
        obj['venue_description'] = ApiClient.convertToType(data['venue_description'], 'String');
      }
      if (data.hasOwnProperty('venue_features')) {
        obj['venue_features'] = ApiClient.convertToType(data['venue_features'], 'String');
      }
      if (data.hasOwnProperty('venue_policy')) {
        obj['venue_policy'] = ApiClient.convertToType(data['venue_policy'], 'String');
      }
      if (data.hasOwnProperty('neighborhood')) {
        obj['neighborhood'] = ApiClient.convertToType(data['neighborhood'], 'String');
      }
      if (data.hasOwnProperty('address_street')) {
        obj['address_street'] = ApiClient.convertToType(data['address_street'], 'String');
      }
      if (data.hasOwnProperty('address_city')) {
        obj['address_city'] = ApiClient.convertToType(data['address_city'], 'String');
      }
      if (data.hasOwnProperty('address_state')) {
        obj['address_state'] = ApiClient.convertToType(data['address_state'], 'String');
      }
      if (data.hasOwnProperty('address_postal_code')) {
        obj['address_postal_code'] = ApiClient.convertToType(data['address_postal_code'], 'String');
      }
      if (data.hasOwnProperty('address_country')) {
        obj['address_country'] = ApiClient.convertToType(data['address_country'], 'String');
      }
      if (data.hasOwnProperty('temporarily_closed')) {
        obj['temporarily_closed'] = ApiClient.convertToType(data['temporarily_closed'], 'String');
      }
      if (data.hasOwnProperty('operating_hours')) {
        obj['operating_hours'] = ApiClient.convertToType(data['operating_hours'], 'String');
      }
      if (data.hasOwnProperty('operating_hours_list')) {
        obj['operating_hours_list'] = ApiClient.convertToType(data['operating_hours_list'], 'String');
      }
      if (data.hasOwnProperty('check_in_time')) {
        obj['check_in_time'] = ApiClient.convertToType(data['check_in_time'], 'String');
      }
      if (data.hasOwnProperty('venue_area_size')) {
        obj['venue_area_size'] = ApiClient.convertToType(data['venue_area_size'], 'String');
      }
      if (data.hasOwnProperty('capacity')) {
        obj['capacity'] = ApiClient.convertToType(data['capacity'], 'String');
      }
      if (data.hasOwnProperty('age_minimum')) {
        obj['age_minimum'] = ApiClient.convertToType(data['age_minimum'], 'String');
      }
      if (data.hasOwnProperty('crowd_type')) {
        obj['crowd_type'] = ApiClient.convertToType(data['crowd_type'], 'String');
      }
      if (data.hasOwnProperty('dress_code')) {
        obj['dress_code'] = ApiClient.convertToType(data['dress_code'], 'String');
      }
      if (data.hasOwnProperty('price_rating')) {
        obj['price_rating'] = ApiClient.convertToType(data['price_rating'], 'String');
      }
      if (data.hasOwnProperty('music_genres')) {
        obj['music_genres'] = ApiClient.convertToType(data['music_genres'], 'String');
      }
      if (data.hasOwnProperty('venue_rooms')) {
        obj['venue_rooms'] = ApiClient.convertToType(data['venue_rooms'], 'String');
      }
      if (data.hasOwnProperty('venue_facebook')) {
        obj['venue_facebook'] = ApiClient.convertToType(data['venue_facebook'], 'String');
      }
      if (data.hasOwnProperty('venue_instagram')) {
        obj['venue_instagram'] = ApiClient.convertToType(data['venue_instagram'], 'String');
      }
      if (data.hasOwnProperty('venue_logo')) {
        obj['venue_logo'] = ApiClient.convertToType(data['venue_logo'], 'String');
      }
      if (data.hasOwnProperty('venue_videos')) {
        obj['venue_videos'] = ApiClient.convertToType(data['venue_videos'], 'String');
      }
      if (data.hasOwnProperty('venue_images')) {
        obj['venue_images'] = ApiClient.convertToType(data['venue_images'], 'String');
      }
    }
    return obj;
  }

  /**
   * Venue Id.
   * @member {Number} venue_id
   */
  exports.prototype['venue_id'] = undefined;
  /**
   * Venue Type.
   * @member {String} venue_type
   */
  exports.prototype['venue_type'] = undefined;
  /**
   * Venue Title.
   * @member {String} venue_title
   */
  exports.prototype['venue_title'] = undefined;
  /**
   * Venue Display Name.
   * @member {String} venue_display_title
   */
  exports.prototype['venue_display_title'] = undefined;
  /**
   * Venue Description.
   * @member {String} venue_description
   */
  exports.prototype['venue_description'] = undefined;
  /**
   * an Array of features.
   * @member {String} venue_features
   */
  exports.prototype['venue_features'] = undefined;
  /**
   * Venue Policy.
   * @member {String} venue_policy
   */
  exports.prototype['venue_policy'] = undefined;
  /**
   * Short Description of Area .
   * @member {String} neighborhood
   */
  exports.prototype['neighborhood'] = undefined;
  /**
   * Street Address for the Venue.
   * @member {String} address_street
   */
  exports.prototype['address_street'] = undefined;
  /**
   * City Name.
   * @member {String} address_city
   */
  exports.prototype['address_city'] = undefined;
  /**
   * State location for the venue.
   * @member {String} address_state
   */
  exports.prototype['address_state'] = undefined;
  /**
   * Zip Code for the venue.
   * @member {String} address_postal_code
   */
  exports.prototype['address_postal_code'] = undefined;
  /**
   * Country Code.
   * @member {String} address_country
   */
  exports.prototype['address_country'] = undefined;
  /**
   * Venue Policy.
   * @member {String} temporarily_closed
   */
  exports.prototype['temporarily_closed'] = undefined;
  /**
   * Weekly interval for operating list.
   * @member {String} operating_hours
   */
  exports.prototype['operating_hours'] = undefined;
  /**
   * Array of operation hours.
   * @member {String} operating_hours_list
   */
  exports.prototype['operating_hours_list'] = undefined;
  /**
   * Checking time.
   * @member {String} check_in_time
   */
  exports.prototype['check_in_time'] = undefined;
  /**
   * Venue Policy.
   * @member {String} venue_area_size
   */
  exports.prototype['venue_area_size'] = undefined;
  /**
   * Capacity for the Venue.
   * @member {String} capacity
   */
  exports.prototype['capacity'] = undefined;
  /**
   * Minimum age allowed in the venue.
   * @member {String} age_minimum
   */
  exports.prototype['age_minimum'] = undefined;
  /**
   * Crowd Type Details.
   * @member {String} crowd_type
   */
  exports.prototype['crowd_type'] = undefined;
  /**
   * Array of dress code details.
   * @member {String} dress_code
   */
  exports.prototype['dress_code'] = undefined;
  /**
   * Price Rating value.
   * @member {String} price_rating
   */
  exports.prototype['price_rating'] = undefined;
  /**
   * Array of music genres.
   * @member {String} music_genres
   */
  exports.prototype['music_genres'] = undefined;
  /**
   * Array of rooms for the venues with, capacity, description.
   * @member {String} venue_rooms
   */
  exports.prototype['venue_rooms'] = undefined;
  /**
   * Venue Facebook Account.
   * @member {String} venue_facebook
   */
  exports.prototype['venue_facebook'] = undefined;
  /**
   * Venue Instagram Account.
   * @member {String} venue_instagram
   */
  exports.prototype['venue_instagram'] = undefined;
  /**
   * Venue Logo.
   * @member {String} venue_logo
   */
  exports.prototype['venue_logo'] = undefined;
  /**
   * Array of venues videos.
   * @member {String} venue_videos
   */
  exports.prototype['venue_videos'] = undefined;
  /**
   * Array of venue images.
   * @member {String} venue_images
   */
  exports.prototype['venue_images'] = undefined;



  return exports;
}));


