/**
 * OpenParty API
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenPartyApi);
  }
}(this, function(expect, OpenPartyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenPartyApi.Event();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Event', function() {
    it('should create an instance of Event', function() {
      // uncomment below and update the code to test Event
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be.a(OpenPartyApi.Event);
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property eventTitle (base name: "event_title")', function() {
      // uncomment below and update the code to test the property eventTitle
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property ageMinimum (base name: "age_minimum")', function() {
      // uncomment below and update the code to test the property ageMinimum
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property eventDescription (base name: "event_description")', function() {
      // uncomment below and update the code to test the property eventDescription
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property flyerFilename (base name: "flyer_filename")', function() {
      // uncomment below and update the code to test the property flyerFilename
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property flyerUri (base name: "flyer_uri")', function() {
      // uncomment below and update the code to test the property flyerUri
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property musicGenres (base name: "music_genres")', function() {
      // uncomment below and update the code to test the property musicGenres
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "event_date")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "start_time")', function() {
      // uncomment below and update the code to test the property startTime
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property eventSubtitle (base name: "event_subtitle")', function() {
      // uncomment below and update the code to test the property eventSubtitle
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property venue (base name: "venue")', function() {
      // uncomment below and update the code to test the property venue
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

    it('should have the property featured (base name: "featured")', function() {
      // uncomment below and update the code to test the property featured
      //var instane = new OpenPartyApi.Event();
      //expect(instance).to.be();
    });

  });

}));
