/**
 * OpenParty API
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Event', 'model/Venue', 'api/EventApi', 'api/VenueApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Error'), require('./model/Event'), require('./model/Venue'), require('./api/EventApi'), require('./api/VenueApi'));
  }
}(function(ApiClient, Error, Event, Venue, EventApi, VenueApi) {
  'use strict';

  /**
   * Move_your_app_forward_with_the_OpenParty_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var OpenPartyApi = require('index'); // See note below*.
   * var xxxSvc = new OpenPartyApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new OpenPartyApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new OpenPartyApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new OpenPartyApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event: Event,
    /**
     * The Venue model constructor.
     * @property {module:model/Venue}
     */
    Venue: Venue,
    /**
     * The EventApi service constructor.
     * @property {module:api/EventApi}
     */
    EventApi: EventApi,
    /**
     * The VenueApi service constructor.
     * @property {module:api/VenueApi}
     */
    VenueApi: VenueApi
  };

  return exports;
}));
